// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASGivnGi0HoSdttXiRpImMIxMZVRb4evk',
    appId: '1:721190224150:web:623975cead0ed125815037',
    messagingSenderId: '721190224150',
    projectId: 'rssb-store-app',
    authDomain: 'rssb-store-app.firebaseapp.com',
    storageBucket: 'rssb-store-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFmA5fGcAEa8x_d9APpFojISuISXeq_MQ',
    appId: '1:721190224150:android:d6bd716ca214809b815037',
    messagingSenderId: '721190224150',
    projectId: 'rssb-store-app',
    storageBucket: 'rssb-store-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLTWjP3H5Hml1SE1cQJF9OwDR-3B-JA9k',
    appId: '1:721190224150:ios:57e3a97703dac51f815037',
    messagingSenderId: '721190224150',
    projectId: 'rssb-store-app',
    storageBucket: 'rssb-store-app.firebasestorage.app',
    iosBundleId: 'com.rssb.store.rssbStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLTWjP3H5Hml1SE1cQJF9OwDR-3B-JA9k',
    appId: '1:721190224150:ios:57e3a97703dac51f815037',
    messagingSenderId: '721190224150',
    projectId: 'rssb-store-app',
    storageBucket: 'rssb-store-app.firebasestorage.app',
    iosBundleId: 'com.rssb.store.rssbStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASGivnGi0HoSdttXiRpImMIxMZVRb4evk',
    appId: '1:721190224150:web:a067bf73ba24f985815037',
    messagingSenderId: '721190224150',
    projectId: 'rssb-store-app',
    authDomain: 'rssb-store-app.firebaseapp.com',
    storageBucket: 'rssb-store-app.firebasestorage.app',
  );
}
